# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: Node.js

on: [push]
# See supported Node.js release schedule at https://nodejs.org/en/about/releases/
env:
  NODE_VERSION: 24

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        check-latest: true
        # cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run manifest:build

# End.
